services:
  cosmos-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: "5"
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: "true"
    ports:
      - "8081:8081"
      - "10251-10254:10251-10254"
    volumes:
      - cosmos-data:/data/db

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite-blob --blobHost 0.0.0.0"
    ports:
      - "10000:10000"
    volumes:
      - azurite-data:/data

volumes:
  cosmos-data:
  azurite-data:
